-- YL milk powder warehouse replenishment mockup tables
-- Source: docs/奶粉分仓补货数据库表字段.xlsx

CREATE TABLE IF NOT EXISTS yl_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_code VARCHAR(16) NOT NULL,
    product_name VARCHAR(128),
    trade_name VARCHAR(64),
    brand VARCHAR(32),
    weight_unit NUMERIC(15,5) NOT NULL DEFAULT '0.00000',
    specification INTEGER NOT NULL DEFAULT '1',
    weight NUMERIC(11,8) NOT NULL DEFAULT '0.00000000',
    sort INTEGER NOT NULL DEFAULT '99999',
    remark VARCHAR(255),
    is_delete SMALLINT NOT NULL DEFAULT '0',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator VARCHAR(50),
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifier VARCHAR(50),
    business VARCHAR(32),
    business_code VARCHAR(16),
    price NUMERIC(15,5),
    pack_type VARCHAR(32),
    volume VARCHAR(16),
    pro_series VARCHAR(64),
    PRIMARY KEY (id)
);

COMMENT ON TABLE yl_product IS '产品主数据';

COMMENT ON COLUMN yl_product.id IS 'id';

COMMENT ON COLUMN yl_product.product_code IS '产品编码';

COMMENT ON COLUMN yl_product.product_name IS '产品名称';

COMMENT ON COLUMN yl_product.trade_name IS '品名';

COMMENT ON COLUMN yl_product.brand IS '品牌';

COMMENT ON COLUMN yl_product.weight_unit IS '单个重量(克)';

COMMENT ON COLUMN yl_product.specification IS '规格';

COMMENT ON COLUMN yl_product.weight IS '重量(吨) = 单个重量*规格/1000';

COMMENT ON COLUMN yl_product.sort IS '排序标识';

COMMENT ON COLUMN yl_product.remark IS '备注';

COMMENT ON COLUMN yl_product.is_delete IS '0-正常  1删除禁用';

COMMENT ON COLUMN yl_product.create_time IS '创建时间';

COMMENT ON COLUMN yl_product.creator IS '创建人';

COMMENT ON COLUMN yl_product.update_time IS '更新时间';

COMMENT ON COLUMN yl_product.modifier IS '更新人';

COMMENT ON COLUMN yl_product.business IS '事业部';

COMMENT ON COLUMN yl_product.business_code IS '事业部编码';

COMMENT ON COLUMN yl_product.price IS '单价';

COMMENT ON COLUMN yl_product.pack_type IS '包装类别';

COMMENT ON COLUMN yl_product.volume IS '实测体积(m³)';

COMMENT ON COLUMN yl_product.pro_series IS 'N-1调拨滞留';

CREATE TABLE IF NOT EXISTS yl_warehouse (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    business VARCHAR(32) NOT NULL,
    business_code VARCHAR(16) NOT NULL,
    site_type SMALLINT NOT NULL DEFAULT '0',
    site_code VARCHAR(16),
    site_desc VARCHAR(255),
    site_name VARCHAR(128),
    sort INTEGER NOT NULL DEFAULT '99999',
    remark VARCHAR(255),
    PRIMARY KEY (id)
);

COMMENT ON TABLE yl_warehouse IS '仓主数据';

COMMENT ON COLUMN yl_warehouse.id IS 'id';

COMMENT ON COLUMN yl_warehouse.business IS '所属事业部';

COMMENT ON COLUMN yl_warehouse.business_code IS '所属事业部编码';

COMMENT ON COLUMN yl_warehouse.site_type IS '仓库类型(0基地仓  1销售仓)';

COMMENT ON COLUMN yl_warehouse.site_code IS '仓库编码';

COMMENT ON COLUMN yl_warehouse.site_desc IS '仓库全称';

COMMENT ON COLUMN yl_warehouse.site_name IS '仓库简称';

COMMENT ON COLUMN yl_warehouse.sort IS '排序标识';

COMMENT ON COLUMN yl_warehouse.remark IS '备注';

CREATE TABLE IF NOT EXISTS yl_sales_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ds VARCHAR(32),
    plan_year INTEGER NOT NULL,
    plan_month SMALLINT NOT NULL,
    product_code VARCHAR(32) NOT NULL,
    product_name VARCHAR(255),
    site_code VARCHAR(16),
    site_name VARCHAR(128),
    site_type SMALLINT NOT NULL DEFAULT '0',
    plan_num NUMERIC(15,5) DEFAULT '0.00000',
    next_plan_num NUMERIC(15,5) DEFAULT '0.00000',
    avg_plan_num NUMERIC(15,5) DEFAULT '0.00000',
    next_avg_plan_num NUMERIC(15,5) DEFAULT '0.00000',
    remark VARCHAR(255),
    PRIMARY KEY (id)
);

COMMENT ON TABLE yl_sales_plan IS '销售计划';

COMMENT ON COLUMN yl_sales_plan.id IS 'id';

COMMENT ON COLUMN yl_sales_plan.ds IS '同步日期';

COMMENT ON COLUMN yl_sales_plan.plan_year IS '年份 比如:2023';

COMMENT ON COLUMN yl_sales_plan.plan_month IS '月份 比如:5';

COMMENT ON COLUMN yl_sales_plan.product_code IS '产品编码';

COMMENT ON COLUMN yl_sales_plan.product_name IS '产品名称';

COMMENT ON COLUMN yl_sales_plan.site_code IS '仓库编码';

COMMENT ON COLUMN yl_sales_plan.site_name IS '仓库名称';

COMMENT ON COLUMN yl_sales_plan.site_type IS '仓库类型(0基地仓  1销售仓)';

COMMENT ON COLUMN yl_sales_plan.plan_num IS '本月销售计划(件）';

COMMENT ON COLUMN yl_sales_plan.next_plan_num IS '下月销售计划(件）';

COMMENT ON COLUMN yl_sales_plan.avg_plan_num IS '本月日均销售计划(件)';

COMMENT ON COLUMN yl_sales_plan.next_avg_plan_num IS '次月日均销售计划(件)';

COMMENT ON COLUMN yl_sales_plan.remark IS '备注';

CREATE TABLE IF NOT EXISTS yl_spot_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ds VARCHAR(32),
    product_code VARCHAR(32) NOT NULL,
    product_name VARCHAR(255),
    site_code VARCHAR(16),
    site_name VARCHAR(128),
    site_type SMALLINT NOT NULL DEFAULT '0',
    produce_date DATE NOT NULL,
    status VARCHAR(32),
    store_num NUMERIC(15,5) DEFAULT '0.00000',
    invetory_deduct_sum NUMERIC(15,5),
    actual_order NUMERIC(15,5),
    remark VARCHAR(255),
    is_delete SMALLINT NOT NULL DEFAULT '0',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator VARCHAR(50) DEFAULT '中台',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifier VARCHAR(50) DEFAULT '中台',
    actual_num NUMERIC(15,5) DEFAULT '0.00000',
    tms_dist_num NUMERIC(15,5) DEFAULT '0.00000',
    wms_dist_num NUMERIC(15,5) DEFAULT '0.00000',
    oms_dist_num NUMERIC(15,5) DEFAULT '0.00000',
    invetory_box_sum NUMERIC(15,5) DEFAULT '0.00000',
    inventory_month_num NUMERIC(15,5) DEFAULT '0.00000',
    inventory_yes_num NUMERIC(15,5) DEFAULT '0.00000',
    PRIMARY KEY (id)
);

COMMENT ON TABLE yl_spot_inventory IS '现货库存';

COMMENT ON COLUMN yl_spot_inventory.id IS 'id';

COMMENT ON COLUMN yl_spot_inventory.ds IS '同步日期';

COMMENT ON COLUMN yl_spot_inventory.product_code IS '产品编码';

COMMENT ON COLUMN yl_spot_inventory.product_name IS '产品名称';

COMMENT ON COLUMN yl_spot_inventory.site_code IS '仓库编码';

COMMENT ON COLUMN yl_spot_inventory.site_name IS '仓库名称';

COMMENT ON COLUMN yl_spot_inventory.site_type IS '仓库类型(0基地仓  1销售仓)';

COMMENT ON COLUMN yl_spot_inventory.produce_date IS '生产日期';

COMMENT ON COLUMN yl_spot_inventory.status IS '库存状态';

COMMENT ON COLUMN yl_spot_inventory.store_num IS '库存(件）';

COMMENT ON COLUMN yl_spot_inventory.invetory_deduct_sum IS '抵扣后库存-(合格的现货库存+未执行订单的调拨计划)';

COMMENT ON COLUMN yl_spot_inventory.actual_order IS '实际库存(生产实际库存)';

COMMENT ON COLUMN yl_spot_inventory.remark IS '备注';

COMMENT ON COLUMN yl_spot_inventory.is_delete IS '0-正常  1删除禁用';

COMMENT ON COLUMN yl_spot_inventory.create_time IS '创建时间';

COMMENT ON COLUMN yl_spot_inventory.creator IS '创建人';

COMMENT ON COLUMN yl_spot_inventory.update_time IS '更新时间';

COMMENT ON COLUMN yl_spot_inventory.modifier IS '更新人';

COMMENT ON COLUMN yl_spot_inventory.actual_num IS '库存总件数';

COMMENT ON COLUMN yl_spot_inventory.tms_dist_num IS 'TMS未一键下发数量';

COMMENT ON COLUMN yl_spot_inventory.wms_dist_num IS 'WMS开放待扣除数量';

COMMENT ON COLUMN yl_spot_inventory.oms_dist_num IS '履约中台未审核数量';

COMMENT ON COLUMN yl_spot_inventory.invetory_box_sum IS '礼盒库存';

COMMENT ON COLUMN yl_spot_inventory.inventory_month_num IS '本月累计入库量';

COMMENT ON COLUMN yl_spot_inventory.inventory_yes_num IS '昨日入库量';

CREATE TABLE IF NOT EXISTS yl_transit_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ds VARCHAR(32),
    product_code VARCHAR(32) NOT NULL,
    product_name VARCHAR(255),
    from_site_code VARCHAR(16) NOT NULL,
    from_site_name VARCHAR(64),
    from_site_type SMALLINT NOT NULL DEFAULT '0',
    to_site_code VARCHAR(16) NOT NULL,
    to_site_name VARCHAR(64),
    to_site_type SMALLINT NOT NULL DEFAULT '0',
    store_transit NUMERIC(15,5) DEFAULT '0.00000',
    remark VARCHAR(255),
    is_delete SMALLINT NOT NULL DEFAULT '0',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator VARCHAR(50) DEFAULT '中台',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifier VARCHAR(50) DEFAULT '中台',
    issued_not_dispatched NUMERIC(15,5),
    trans_order_not_dispatched NUMERIC(15,5),
    PRIMARY KEY (id)
);

COMMENT ON TABLE yl_transit_inventory IS '在途库存';

COMMENT ON COLUMN yl_transit_inventory.id IS 'id';

COMMENT ON COLUMN yl_transit_inventory.ds IS '同步日期';

COMMENT ON COLUMN yl_transit_inventory.product_code IS '产品编码';

COMMENT ON COLUMN yl_transit_inventory.product_name IS '产品名称';

COMMENT ON COLUMN yl_transit_inventory.from_site_code IS '发货仓编码';

COMMENT ON COLUMN yl_transit_inventory.from_site_name IS '发货仓名称';

COMMENT ON COLUMN yl_transit_inventory.from_site_type IS '发货仓类型(0基地仓  1销售仓)';

COMMENT ON COLUMN yl_transit_inventory.to_site_code IS '收货仓编码';

COMMENT ON COLUMN yl_transit_inventory.to_site_name IS '收货仓名称';

COMMENT ON COLUMN yl_transit_inventory.to_site_type IS '收货仓类型(0基地仓  1销售仓)';

COMMENT ON COLUMN yl_transit_inventory.store_transit IS '在途总量（件）';

COMMENT ON COLUMN yl_transit_inventory.remark IS '备注';

COMMENT ON COLUMN yl_transit_inventory.is_delete IS '0-正常  1删除禁用';

COMMENT ON COLUMN yl_transit_inventory.create_time IS '创建时间';

COMMENT ON COLUMN yl_transit_inventory.creator IS '创建人';

COMMENT ON COLUMN yl_transit_inventory.update_time IS '更新时间';

COMMENT ON COLUMN yl_transit_inventory.modifier IS '更新人';

COMMENT ON COLUMN yl_transit_inventory.issued_not_dispatched IS '已下发未发货（未执行调拨计划量）';

COMMENT ON COLUMN yl_transit_inventory.trans_order_not_dispatched IS '调拨单未发货';

CREATE TABLE IF NOT EXISTS yl_actual_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ds VARCHAR(32),
    sell_year INTEGER NOT NULL,
    sell_month SMALLINT NOT NULL,
    product_code VARCHAR(32) NOT NULL,
    product_name VARCHAR(255),
    site_code VARCHAR(16),
    site_name VARCHAR(128),
    site_type SMALLINT NOT NULL DEFAULT '0',
    sell_num NUMERIC(15,5) DEFAULT '0.00000',
    out_put_num NUMERIC(15,5) DEFAULT '0.00000',
    sell_num_avg NUMERIC(15,5) DEFAULT '0.00000',
    available_quantity NUMERIC(15,5) DEFAULT '0.00000',
    remark VARCHAR(255),
    is_delete SMALLINT NOT NULL DEFAULT '0',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator VARCHAR(50) DEFAULT '中台',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifier VARCHAR(50) DEFAULT '中台',
    pick_store NUMERIC(15,5),
    unshipped_orders NUMERIC(15,5) DEFAULT '0.00000',
    PRIMARY KEY (id)
);

COMMENT ON TABLE yl_actual_sales IS '实际销量';

COMMENT ON COLUMN yl_actual_sales.id IS 'id';

COMMENT ON COLUMN yl_actual_sales.ds IS '同步日期';

COMMENT ON COLUMN yl_actual_sales.sell_year IS '年份 比如:2023';

COMMENT ON COLUMN yl_actual_sales.sell_month IS '月份 比如:5';

COMMENT ON COLUMN yl_actual_sales.product_code IS '产品编码';

COMMENT ON COLUMN yl_actual_sales.product_name IS '产品名称';

COMMENT ON COLUMN yl_actual_sales.site_code IS '仓库编码';

COMMENT ON COLUMN yl_actual_sales.site_name IS '仓库名称';

COMMENT ON COLUMN yl_actual_sales.site_type IS '仓库类型(0基地仓  1销售仓)';

COMMENT ON COLUMN yl_actual_sales.sell_num IS '当月订单(件)-实际销量';

COMMENT ON COLUMN yl_actual_sales.out_put_num IS '当月已出库数量(件)';

COMMENT ON COLUMN yl_actual_sales.sell_num_avg IS '前3月平均销量(件)';

COMMENT ON COLUMN yl_actual_sales.available_quantity IS '当月未发货量(件)';

COMMENT ON COLUMN yl_actual_sales.remark IS '备注';

COMMENT ON COLUMN yl_actual_sales.is_delete IS '0-正常  1删除禁用';

COMMENT ON COLUMN yl_actual_sales.create_time IS '创建时间';

COMMENT ON COLUMN yl_actual_sales.creator IS '创建人';

COMMENT ON COLUMN yl_actual_sales.update_time IS '更新时间';

COMMENT ON COLUMN yl_actual_sales.modifier IS '更新人';

COMMENT ON COLUMN yl_actual_sales.pick_store IS '挑库量';

COMMENT ON COLUMN yl_actual_sales.unshipped_orders IS '当月真实未发货订单量';

CREATE TABLE IF NOT EXISTS yl_base_warehouse_inventory_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    adjust_date DATE NOT NULL,
    business_code VARCHAR(16) NOT NULL,
    product_code VARCHAR(32) NOT NULL,
    product_name VARCHAR(255),
    weight NUMERIC(15,5),
    pro_series VARCHAR(64),
    from_site_code VARCHAR(16) NOT NULL,
    from_site_name VARCHAR(64),
    month_store_in NUMERIC(15,5),
    now_store_in NUMERIC(15,5),
    big_date VARCHAR(500),
    big_date_num NUMERIC(15,5),
    days_list TEXT,
    from_store_transit NUMERIC(15,5),
    from_store_num_d NUMERIC(15,5),
    from_store_num_h NUMERIC(15,5),
    to_jd_site_list TEXT,
    months_list TEXT,
    PRIMARY KEY (id)
);

COMMENT ON TABLE yl_base_warehouse_inventory_report IS '基地仓库存监控报表';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.id IS 'id';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.adjust_date IS '调整日期';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.business_code IS '发货仓所属事业部编码';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.product_code IS '产品编码';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.product_name IS '产品名称';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.weight IS '重量';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.pro_series IS '产品系列';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.from_site_code IS '发货仓编码';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.from_site_name IS '发货仓名称';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.month_store_in IS '本月累计入库量';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.now_store_in IS '今日入库量';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.big_date IS '大日期';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.big_date_num IS '大日期数量';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.days_list IS '库存待检产品日期数量';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.from_store_transit IS '发货仓在途库存';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.from_store_num_d IS '发货仓现货库存(件)-待检';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.from_store_num_h IS '发货仓现货库存(件)-合格';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.to_jd_site_list IS '收货仓-基地仓合集';

COMMENT ON COLUMN yl_base_warehouse_inventory_report.months_list IS '\r\n生产月份库存+在途生产月份及数量';

CREATE TABLE IF NOT EXISTS yl_national_sales_warehouse_inventory_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    adjust_date DATE NOT NULL,
    business_code VARCHAR(16),
    product_code VARCHAR(32) NOT NULL,
    product_name VARCHAR(255),
    weight NUMERIC(15,5),
    pro_series VARCHAR(64),
    area_plan NUMERIC(15,5),
    from_stock_rate_before VARCHAR(16),
    order_completion_rate VARCHAR(16),
    sell_completion_rate VARCHAR(16),
    out_put_num NUMERIC(15,5),
    out_put_area NUMERIC(15,5),
    out_put_ec NUMERIC(15,5),
    to_jd_site_list TEXT,
    from_store_transit NUMERIC(15,5),
    from_store_num_d NUMERIC(15,5),
    from_store_num_h NUMERIC(15,5),
    from_store_num_lh_d NUMERIC(15,5),
    from_store_num_lh_h NUMERIC(15,5),
    total_unship NUMERIC(15,5),
    today_plan_ship NUMERIC(15,5),
    remain_unship NUMERIC(15,5),
    ec_inquiry_cnt NUMERIC(15,5),
    last_month_unship NUMERIC(15,5),
    ship_gap NUMERIC(15,5),
    order_gap NUMERIC(15,5),
    jd_big_date VARCHAR(500),
    xs_big_date TEXT,
    jd_big_date_num NUMERIC(15,5),
    xs_big_date_num NUMERIC(15,5),
    next_plan_num NUMERIC(15,5),
    xs_months_list TEXT,
    jd_months_list TEXT,
    next_avg_plan_num NUMERIC(15,5),
    avg_plan_num NUMERIC(15,5),
    sell_num NUMERIC(15,5),
    plan_num NUMERIC(15,5),
    issued_not_dispatched NUMERIC(15,5),
    PRIMARY KEY (id)
);

COMMENT ON TABLE yl_national_sales_warehouse_inventory_report IS '全国销售仓库存监控报表';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.id IS 'id';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.adjust_date IS '调整日期';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.business_code IS '发货仓所属事业部编码';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.product_code IS '产品编码';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.product_name IS '产品名称';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.weight IS '重量';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.pro_series IS '产品系列';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.area_plan IS '区域计划';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.from_stock_rate_before IS '生产备货率（分配前）';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.order_completion_rate IS '订单完成率= (当月未发货量 +本月累出）/销售计划';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.sell_completion_rate IS '销售完成率  本月累出 /销售计划 ';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.out_put_num IS '本月累计出货合计';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.out_put_area IS '累计出货 - 区域';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.out_put_ec IS '累计出货 - 电商';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.to_jd_site_list IS '收货仓-基地仓合集';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.from_store_transit IS '常规品项在途（待检+合格）';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.from_store_num_d IS '常规品项实际库存 - 待检';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.from_store_num_h IS '常规品项实际库存 - 合格';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.from_store_num_lh_d IS '礼盒库存 - 待检';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.from_store_num_lh_h IS '礼盒库存 - 合格';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.total_unship IS '未发订单 - 总未发货量';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.today_plan_ship IS '未发订单 - 今日计划发运';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.remain_unship IS '未发订单 - 剩余未发';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.ec_inquiry_cnt IS '未发订单 - 电商平台询单量';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.last_month_unship IS '未发订单 - 其中上月未发量';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.ship_gap IS '发货缺口   现货库存 - 未发量';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.order_gap IS '订单缺口（现货 + 在途 - 未发）';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.jd_big_date IS '基地大日期';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.xs_big_date IS '销售大日期';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.jd_big_date_num IS '基地大日期数量';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.xs_big_date_num IS '销售大日期数量';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.next_plan_num IS '下月销售计划';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.xs_months_list IS '销售\r\n库存生产月份即数量';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.jd_months_list IS '基地库存生产月份即数量';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.next_avg_plan_num IS '次月日均销售计划(件)';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.avg_plan_num IS '本月日均销售计划(件)';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.sell_num IS '当月订单(件)-实际销量';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.plan_num IS '本月销售计划(件）';

COMMENT ON COLUMN yl_national_sales_warehouse_inventory_report.issued_not_dispatched IS '已下发未发货';

CREATE TABLE IF NOT EXISTS yl_sales_warehouse_inventory_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    adjust_date DATE NOT NULL,
    business_code VARCHAR(16) NOT NULL,
    product_code VARCHAR(32) NOT NULL,
    product_name VARCHAR(255),
    weight NUMERIC(15,5),
    pro_series VARCHAR(64),
    from_site_code VARCHAR(16) NOT NULL,
    from_site_name VARCHAR(64),
    area_plan NUMERIC(15,5),
    from_stock_rate_before VARCHAR(16),
    order_completion_rate VARCHAR(16),
    sell_completion_rate VARCHAR(16),
    out_put_num NUMERIC(15,5),
    out_put_area NUMERIC(15,5),
    out_put_ec NUMERIC(15,5),
    to_jd_site_list TEXT,
    from_store_transit NUMERIC(15,5),
    from_store_num_d NUMERIC(15,5),
    from_store_num_h NUMERIC(15,5),
    from_store_num_lh_d NUMERIC(15,5),
    from_store_num_lh_h NUMERIC(15,5),
    total_unship NUMERIC(15,5),
    today_plan_ship NUMERIC(15,5),
    remain_unship NUMERIC(15,5),
    ec_inquiry_cnt NUMERIC(15,5),
    last_month_unship NUMERIC(15,5),
    ship_gap NUMERIC(15,5),
    order_gap NUMERIC(15,5),
    big_date VARCHAR(500),
    big_date_num NUMERIC(15,5),
    next_plan_num NUMERIC(15,5),
    months_list TEXT,
    next_avg_plan_num NUMERIC(15,5),
    avg_plan_num NUMERIC(15,5),
    sell_num NUMERIC(15,5),
    plan_num NUMERIC(15,5),
    issued_not_dispatched NUMERIC(15,5),
    is_delete SMALLINT NOT NULL DEFAULT '0',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator VARCHAR(50) DEFAULT '',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifier VARCHAR(50) DEFAULT '',
    ec_inquiry_num NUMERIC(15,5),
    ec_pre_occupancy_num NUMERIC(15,5),
    PRIMARY KEY (id)
);

COMMENT ON TABLE yl_sales_warehouse_inventory_report IS '销售仓库存监控报表';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.id IS 'id';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.adjust_date IS '调整日期';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.business_code IS '发货仓所属事业部编码';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.product_code IS '产品编码';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.product_name IS '产品名称';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.weight IS '重量';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.pro_series IS '产品系列';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.from_site_code IS '发货仓编码';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.from_site_name IS '发货仓名称';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.area_plan IS '区域计划';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.from_stock_rate_before IS '生产备货率（分配前）';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.order_completion_rate IS '订单完成率= (当月未发货量 +本月累出）/销售计划';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.sell_completion_rate IS '销售完成率  本月累出 /销售计划 ';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.out_put_num IS '本月累计出货合计';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.out_put_area IS '累计出货 - 区域';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.out_put_ec IS '累计出货 - 电商';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.to_jd_site_list IS '收货仓-基地仓合集';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.from_store_transit IS '常规品项在途（待检+合格）';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.from_store_num_d IS '常规品项实际库存 - 待检';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.from_store_num_h IS '常规品项实际库存 - 合格';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.from_store_num_lh_d IS '礼盒库存 - 待检';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.from_store_num_lh_h IS '礼盒库存 - 合格';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.total_unship IS '未发订单 - 总未发货量';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.today_plan_ship IS '未发订单 - 今日计划发运';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.remain_unship IS '未发订单 - 剩余未发';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.ec_inquiry_cnt IS '未发订单 - 电商平台询单量';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.last_month_unship IS '未发订单 - 其中上月未发量';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.ship_gap IS '发货缺口   现货库存 - 未发量';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.order_gap IS '订单缺口（现货 + 在途 - 未发）';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.big_date IS '大日期';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.big_date_num IS '大日期数量';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.next_plan_num IS '下月销售计划';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.months_list IS '\r\n库存生产月份即数量';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.next_avg_plan_num IS '次月日均销售计划(件)';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.avg_plan_num IS '本月日均销售计划(件)';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.sell_num IS '当月订单(件)-实际销量';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.plan_num IS '本月销售计划(件）';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.issued_not_dispatched IS '已下发未发货';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.is_delete IS '0-正常  1删除禁用';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.create_time IS '创建时间';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.creator IS '创建人';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.update_time IS '更新时间';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.modifier IS '更新人';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.ec_inquiry_num IS '电商询单量';

COMMENT ON COLUMN yl_sales_warehouse_inventory_report.ec_pre_occupancy_num IS '电商预占量';

CREATE TABLE IF NOT EXISTS yl_lateral_transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    adjust_date DATE NOT NULL,
    business VARCHAR(32) NOT NULL,
    business_code VARCHAR(16) NOT NULL,
    product_code VARCHAR(32) NOT NULL,
    product_name VARCHAR(255),
    from_site_code VARCHAR(16) NOT NULL,
    from_site_name VARCHAR(64),
    from_store_num NUMERIC(15,5),
    from_remaining NUMERIC(15,5),
    from_store_transit NUMERIC(15,5),
    from_big_date_num NUMERIC(15,5),
    from_out_put_num NUMERIC(15,5),
    from_plan_num NUMERIC(15,5),
    from_stock_rate_before VARCHAR(16),
    from_stock_rate_after VARCHAR(16),
    to_site_code VARCHAR(16) NOT NULL,
    to_site_name VARCHAR(64),
    trans_num_jh NUMERIC(15,5),
    trans_num NUMERIC(15,5),
    to_store_num NUMERIC(15,5),
    to_store_transit NUMERIC(15,5),
    to_big_date_num NUMERIC(15,5),
    to_out_put_num NUMERIC(15,5),
    to_plan_num NUMERIC(15,5),
    to_stock_rate_before VARCHAR(16),
    to_stock_rate_after VARCHAR(16),
    to_sell_num NUMERIC(15,5),
    to_sell_num_avg NUMERIC(15,5),
    reason VARCHAR(255),
    remark VARCHAR(255),
    push_num NUMERIC(15,5),
    push_time TIMESTAMP,
    push_user VARCHAR(50) DEFAULT '',
    is_delete SMALLINT NOT NULL DEFAULT '0',
    PRIMARY KEY (id)
);

COMMENT ON TABLE yl_lateral_transfer IS '奶粉分仓补调 - 横向调拨';

COMMENT ON COLUMN yl_lateral_transfer.id IS 'id';

COMMENT ON COLUMN yl_lateral_transfer.adjust_date IS '调整日期';

COMMENT ON COLUMN yl_lateral_transfer.business IS '发货仓所属事业部';

COMMENT ON COLUMN yl_lateral_transfer.business_code IS '发货仓所属事业部编码';

COMMENT ON COLUMN yl_lateral_transfer.product_code IS '产品编码';

COMMENT ON COLUMN yl_lateral_transfer.product_name IS '产品名称';

COMMENT ON COLUMN yl_lateral_transfer.from_site_code IS '发货仓编码';

COMMENT ON COLUMN yl_lateral_transfer.from_site_name IS '发货仓名称';

COMMENT ON COLUMN yl_lateral_transfer.from_store_num IS '发货仓现货库存(件)';

COMMENT ON COLUMN yl_lateral_transfer.from_remaining IS '发货仓剩余现货库存(实时保存后端处理,否则前端计算)-现货库存-横向调拨建议和';

COMMENT ON COLUMN yl_lateral_transfer.from_store_transit IS '发货仓在途库存(件)';

COMMENT ON COLUMN yl_lateral_transfer.from_big_date_num IS '发货仓大日期库存(件)';

COMMENT ON COLUMN yl_lateral_transfer.from_out_put_num IS '发货仓本月已出库(件)';

COMMENT ON COLUMN yl_lateral_transfer.from_plan_num IS '发货仓本月销售计划(件）';

COMMENT ON COLUMN yl_lateral_transfer.from_stock_rate_before IS '发货仓均衡前生产备货率-（现货库存+在途+本月已出库 ）/销售计划';

COMMENT ON COLUMN yl_lateral_transfer.from_stock_rate_after IS '发货仓均衡后生产备货率(实时保存后端处理,否则前端计算)-（现货库存+在途+本月已出库 - 横向调拨建议和）/销售计划';

COMMENT ON COLUMN yl_lateral_transfer.to_site_code IS '收货仓编码';

COMMENT ON COLUMN yl_lateral_transfer.to_site_name IS '收货仓名称';

COMMENT ON COLUMN yl_lateral_transfer.trans_num_jh IS '京慧建议量（件）';

COMMENT ON COLUMN yl_lateral_transfer.trans_num IS '分配量（件）-初始化与建议量一致';

COMMENT ON COLUMN yl_lateral_transfer.to_store_num IS '收货仓现货库存(件)';

COMMENT ON COLUMN yl_lateral_transfer.to_store_transit IS '收货仓在途库存(件)';

COMMENT ON COLUMN yl_lateral_transfer.to_big_date_num IS '收货仓大日期库存(件)';

COMMENT ON COLUMN yl_lateral_transfer.to_out_put_num IS '收货仓本月已出库(件)';

COMMENT ON COLUMN yl_lateral_transfer.to_plan_num IS '收货仓本月销售计划(件）';

COMMENT ON COLUMN yl_lateral_transfer.to_stock_rate_before IS '收货仓均衡前生产备货率-（现货库存+在途+本月已出库 ）/销售计划';

COMMENT ON COLUMN yl_lateral_transfer.to_stock_rate_after IS '收货仓均衡后生产备货率(实时保存后端处理,否则前端计算)-（现货库存+在途+本月已出库 + 横向调拨建议）/销售计划';

COMMENT ON COLUMN yl_lateral_transfer.to_sell_num IS '收货仓当月订单(件)-实际销量';

COMMENT ON COLUMN yl_lateral_transfer.to_sell_num_avg IS '收货仓前3月平均销量(件)';

COMMENT ON COLUMN yl_lateral_transfer.reason IS '修改原因';

COMMENT ON COLUMN yl_lateral_transfer.remark IS '备注';

COMMENT ON COLUMN yl_lateral_transfer.push_num IS '下发量';

COMMENT ON COLUMN yl_lateral_transfer.push_time IS '下发时间';

COMMENT ON COLUMN yl_lateral_transfer.push_user IS '下发人';

COMMENT ON COLUMN yl_lateral_transfer.is_delete IS '0-正常  1删除禁用';

CREATE TABLE IF NOT EXISTS yl_forward_transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    adjust_date DATE NOT NULL,
    business VARCHAR(32) NOT NULL,
    business_code VARCHAR(16) NOT NULL,
    product_code VARCHAR(32) NOT NULL,
    product_name VARCHAR(255),
    from_site_code VARCHAR(16) NOT NULL,
    from_site_name VARCHAR(64),
    from_store_num_d NUMERIC(15,5),
    from_store_num_h NUMERIC(15,5),
    from_store_transit NUMERIC(15,5),
    from_store_transit_zt NUMERIC(15,5),
    from_available NUMERIC(15,5),
    from_reserve_jh NUMERIC(15,5),
    from_reserve NUMERIC(15,5),
    to_site_code VARCHAR(16) NOT NULL,
    to_site_name VARCHAR(64),
    trans_num_jh NUMERIC(15,5),
    trans_num NUMERIC(15,5),
    to_store_num NUMERIC(15,5),
    to_store_transit NUMERIC(15,5),
    to_sell_num NUMERIC(15,5),
    to_out_put_num INTEGER,
    to_plan_num NUMERIC(15,5),
    to_available_quantity NUMERIC(15,5),
    to_avg_plan_num NUMERIC(15,5),
    to_next_avg_plan_num NUMERIC(15,5),
    to_stock_rate_before VARCHAR(16),
    to_stock_rate_after VARCHAR(16),
    to_order_completion_rate VARCHAR(16),
    to_store_day_after VARCHAR(16),
    to_store_day_next VARCHAR(16),
    reason VARCHAR(255),
    remark VARCHAR(255),
    push_num NUMERIC(15,5),
    push_time TIMESTAMP,
    push_user VARCHAR(50),
    PRIMARY KEY (id)
);

COMMENT ON TABLE yl_forward_transfer IS '奶粉分仓补调 - 正向调拨';

COMMENT ON COLUMN yl_forward_transfer.id IS 'id';

COMMENT ON COLUMN yl_forward_transfer.adjust_date IS '调整日期';

COMMENT ON COLUMN yl_forward_transfer.business IS '发货仓所属事业部';

COMMENT ON COLUMN yl_forward_transfer.business_code IS '发货仓所属事业部编码';

COMMENT ON COLUMN yl_forward_transfer.product_code IS '产品编码';

COMMENT ON COLUMN yl_forward_transfer.product_name IS '产品名称';

COMMENT ON COLUMN yl_forward_transfer.from_site_code IS '发货仓编码';

COMMENT ON COLUMN yl_forward_transfer.from_site_name IS '发货仓名称';

COMMENT ON COLUMN yl_forward_transfer.from_store_num_d IS '发货仓现货库存(件)-待检';

COMMENT ON COLUMN yl_forward_transfer.from_store_num_h IS '发货仓现货库存(件)-合格';

COMMENT ON COLUMN yl_forward_transfer.from_store_transit IS '发货仓在途库存(件)';

COMMENT ON COLUMN yl_forward_transfer.from_store_transit_zt IS '发货仓在途库存(件)-中转,中台后面推,目前没有';

COMMENT ON COLUMN yl_forward_transfer.from_available IS '可发量(件)-库存-基地分配总(不含本基地仓)-销售分配总';

COMMENT ON COLUMN yl_forward_transfer.from_reserve_jh IS '预分量(件)-京慧';

COMMENT ON COLUMN yl_forward_transfer.from_reserve IS '预分量(件)-初始与京慧一致';

COMMENT ON COLUMN yl_forward_transfer.to_site_code IS '收货仓编码';

COMMENT ON COLUMN yl_forward_transfer.to_site_name IS '收货仓名称';

COMMENT ON COLUMN yl_forward_transfer.trans_num_jh IS '京慧建议量（件）';

COMMENT ON COLUMN yl_forward_transfer.trans_num IS '分配量（件）-初始化与建议量一致';

COMMENT ON COLUMN yl_forward_transfer.to_store_num IS '收货仓现货库存(件)';

COMMENT ON COLUMN yl_forward_transfer.to_store_transit IS '收货仓在途库存(件)';

COMMENT ON COLUMN yl_forward_transfer.to_sell_num IS '收货仓当月订单(件)-实际销量';

COMMENT ON COLUMN yl_forward_transfer.to_out_put_num IS '本月已出库量';

COMMENT ON COLUMN yl_forward_transfer.to_plan_num IS '收货仓本月销售计划(件）';

COMMENT ON COLUMN yl_forward_transfer.to_available_quantity IS '当月未发货量(件)';

COMMENT ON COLUMN yl_forward_transfer.to_avg_plan_num IS '本月日均销售计划(件)';

COMMENT ON COLUMN yl_forward_transfer.to_next_avg_plan_num IS '次月日均销售计划(件)';

COMMENT ON COLUMN yl_forward_transfer.to_stock_rate_before IS '收货仓均衡前生产备货率-（现货库存+在途+本月已出库 ）/销售计划';

COMMENT ON COLUMN yl_forward_transfer.to_stock_rate_after IS '收货仓均衡后生产备货率(实时保存后端处理,否则前端计算)-（现货库存+在途+本月已出库 + 横向调拨建议）/销售计划';

COMMENT ON COLUMN yl_forward_transfer.to_order_completion_rate IS '订单完成率-本月总销量/本月销售计划';

COMMENT ON COLUMN yl_forward_transfer.to_store_day_after IS '分配后库存天数(实时保存后端处理,否则前端计算)-（现货库存+在途+分配量-当月未发货量）/本月日均销售计划';

COMMENT ON COLUMN yl_forward_transfer.to_store_day_next IS '下月库存天数(实时保存后端处理,否则前端计算)-（现货库存+在途+分配量-当月未发货量）/次月日均销售计划';

COMMENT ON COLUMN yl_forward_transfer.reason IS '修改原因';

COMMENT ON COLUMN yl_forward_transfer.remark IS '备注';

COMMENT ON COLUMN yl_forward_transfer.push_num IS '下发量';

COMMENT ON COLUMN yl_forward_transfer.push_time IS '下发时间';

COMMENT ON COLUMN yl_forward_transfer.push_user IS '下发人';

CREATE TABLE IF NOT EXISTS yl_big_date_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    business VARCHAR(32) NOT NULL,
    business_code VARCHAR(16) NOT NULL,
    site_type SMALLINT NOT NULL DEFAULT '1',
    site_code VARCHAR(16),
    site_name VARCHAR(128),
    product_code VARCHAR(32) NOT NULL,
    product_name VARCHAR(255),
    big_date_num NUMERIC(15,5) DEFAULT '0.00000',
    remark VARCHAR(255),
    PRIMARY KEY (id)
);

COMMENT ON TABLE yl_big_date_inventory IS '分仓大日期库存';

COMMENT ON COLUMN yl_big_date_inventory.id IS 'id';

COMMENT ON COLUMN yl_big_date_inventory.business IS '所属事业部';

COMMENT ON COLUMN yl_big_date_inventory.business_code IS '所属事业部编码';

COMMENT ON COLUMN yl_big_date_inventory.site_type IS '仓库类型(0基地仓  1销售仓),目前只有销售仓';

COMMENT ON COLUMN yl_big_date_inventory.site_code IS '仓库编码';

COMMENT ON COLUMN yl_big_date_inventory.site_name IS '仓库名称';

COMMENT ON COLUMN yl_big_date_inventory.product_code IS '产品编码';

COMMENT ON COLUMN yl_big_date_inventory.product_name IS '产品名称';

COMMENT ON COLUMN yl_big_date_inventory.big_date_num IS '大日期库存(件）';

COMMENT ON COLUMN yl_big_date_inventory.remark IS '备注';

CREATE TABLE IF NOT EXISTS yl_tms_gps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    seq_no INTEGER,
    location_time TIMESTAMP,
    speed_kmh NUMERIC(15,5),
    mileage_km NUMERIC(15,5),
    driving_mileage_km NUMERIC(15,5),
    status VARCHAR(64),
    location VARCHAR(512),
    longitude NUMERIC(12,8),
    latitude NUMERIC(12,8),
    weather VARCHAR(64),
    plate_no VARCHAR(32),
    driver VARCHAR(64),
    driver_phone VARCHAR(32),
    warehouse VARCHAR(128),
    PRIMARY KEY (id)
);

COMMENT ON TABLE yl_tms_gps IS '运输管理系统';

COMMENT ON COLUMN yl_tms_gps.id IS 'id';

COMMENT ON COLUMN yl_tms_gps.seq_no IS '序号';

COMMENT ON COLUMN yl_tms_gps.location_time IS '定位时间';

COMMENT ON COLUMN yl_tms_gps.speed_kmh IS '速度(km/h)';

COMMENT ON COLUMN yl_tms_gps.mileage_km IS '里程(km)';

COMMENT ON COLUMN yl_tms_gps.driving_mileage_km IS '行驶里程(km)';

COMMENT ON COLUMN yl_tms_gps.status IS '状态';

COMMENT ON COLUMN yl_tms_gps.location IS '位置';

COMMENT ON COLUMN yl_tms_gps.longitude IS '经度';

COMMENT ON COLUMN yl_tms_gps.latitude IS '纬度';

COMMENT ON COLUMN yl_tms_gps.weather IS '天气';

COMMENT ON COLUMN yl_tms_gps.plate_no IS '车牌号';

COMMENT ON COLUMN yl_tms_gps.driver IS '司机';

COMMENT ON COLUMN yl_tms_gps.driver_phone IS '司机电话';

COMMENT ON COLUMN yl_tms_gps.warehouse IS '仓库';

CREATE TABLE IF NOT EXISTS yl_wms_waybill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    waybill_no VARCHAR(64),
    customer_name VARCHAR(255),
    erp_order_no VARCHAR(64),
    customer_address VARCHAR(512),
    carrier_name VARCHAR(128),
    PRIMARY KEY (id)
);

COMMENT ON TABLE yl_wms_waybill IS 'WMS';

COMMENT ON COLUMN yl_wms_waybill.id IS 'id';

COMMENT ON COLUMN yl_wms_waybill.waybill_no IS '运单号';

COMMENT ON COLUMN yl_wms_waybill.customer_name IS '客户名称';

COMMENT ON COLUMN yl_wms_waybill.erp_order_no IS 'ERP单号';

COMMENT ON COLUMN yl_wms_waybill.customer_address IS '客户地址';

COMMENT ON COLUMN yl_wms_waybill.carrier_name IS '承运商名称';
